Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GFR.Models;
using Microsoft.AspNet.Identity;

namespace GFR.Controllers
{
    [Authorize]
    public class ReportsController : Controller
    {
        private GuardianshipDB db = new GuardianshipDB();

        private IQueryable<Ward> userWards(string UserID)
        {
            return db.Wards.Where(w => w.UserID == UserID)
                            .Where(w => w.DeletedDate == null);
                
        }
        // GET: Reports
        //public ActionResult Index()
        //{
        //    string UserID = User.Identity.GetUserId();
        //    // var reports = db.Reports.Include(r => r.AspNetUser).Where(r => r.UserID == UserID);
        //    var reports = db.Reports.Where(r => r.UserID == UserID);
        //    reports = db.Reports.Where(r => r.UserID == UserID);
        //    return View(reports.ToList());
        //}
        public ActionResult Index(int? id)
        {
            // id = WardID

            string UserID = User.Identity.GetUserId();
            // var reports = db.Reports.Include(r => r.AspNetUser).Where(r => r.UserID == UserID);
            // var reports = db.Reports.Where(r => r.UserID == UserID);
            GFR.ViewModels.ReportViewModel rvm;
            if (id != null)
            {
                rvm = new ViewModels.ReportViewModel(UserID, id.Value);
            }
            else
            {
                rvm = new ViewModels.ReportViewModel(UserID);
            }
            return View(rvm);

        }

        //public ActionResult SelectWard()
        //{

        //    List<SelectListItem> items = new List<SelectListItem>();

        //    items.Add(new SelectListItem { Text = "Action", Value = "0" });


        //    items.Add(new SelectListItem { Text = "Drama", Value = "1" });

        //    items.Add(new SelectListItem { Text = "Comedy", Value = "2", Selected = true });

        //    items.Add(new SelectListItem { Text = "Science Fiction", Value = "3" });

        //    ViewBag.MovieType = items;

        //    //List<SelectListItem> listItems = new List<SelectListItem>();
        //    //listItems.Add(new SelectListItem
        //    //{
        //    //    Text = "",
        //    //    Value = "0"
        //    //});
        //    //foreach (var item in Model.WardsList.ToList())
        //    //{
        //    //    listItems.Add(new SelectListItem
        //    //    {
        //    //        Text = item.FullName,
        //    //        Value = item.WardID.ToString()
        //    //    });
        //    //}

        //    return View();

        //}

        // GET: Reports/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                // index when no id passed
                return RedirectToAction("Index");
            }
            Report report = db.Reports.Find(id);
            if (report == null)
            {
                return HttpNotFound();
            }
            else if (report.DeletedDate != null)
            {
                // don't show deleted records
                return HttpNotFound();
            }

            ViewBag.UserID = report.UserID;
            return View(report);
        }

        // GET: Reports/Create
        public ActionResult Create(int? id)
        {

            string UserID = User.Identity.GetUserId();
            // var reports = db.Reports.Include(r => r.AspNetUser).Where(r => r.UserID == UserID);
            ViewBag.UserID = UserID;

            
            // non-deleted 
            UserSetting s = new UserSetting();
            Report r = new Report { UserID = UserID };
            
            // set defaults
            List<UserSetting> defaults = db.UserSettings.Where(u => u.UserID == UserID).ToList();

            foreach (UserSetting u in defaults)
            {
                if (u.Setting.ToUpper() == ReportValues.REPORT_SETTING_PERIOD_DURATION.ToUpper())
                {
                    r.PeriodDuration = (ReportValues.DurationTypes)Enum.Parse(typeof(ReportValues.DurationTypes), u.Value);
                    
                }
                else if (u.Setting.ToUpper() == ReportValues.REPORT_SETTING_PERIOD_START_MONTH.ToUpper())
                {
                    r.PeriodStartMonth = (ReportValues.MonthTypes)Enum.Parse(typeof(ReportValues.MonthTypes), u.Value);

                }
                else if (u.Setting.ToUpper() == ReportValues.REPORT_SETTING_PERIOD_START_YEAR.ToUpper())
                {
                    r.PeriodStartYear = Convert.ToInt16(u.Value);

                }
            }

            // ward-specific
            // todo: fix this; it should be the underlying value

            if (id != null)
            {
                r.PeriodStartMonth = (ReportValues.MonthTypes)Enum.Parse(typeof(ReportValues.MonthTypes), db.Wards.Find(id).PeriodStartMonth.ToString());
                r.PeriodDuration = (ReportValues.DurationTypes)Enum.Parse(typeof(ReportValues.DurationTypes), db.Wards.Find(id).PeriodDuration.ToString());

                // todo: set this to the last completed report + duration
                // r.PeriodStartYear = 
                ViewBag.WardID = new SelectList(userWards(UserID), "WardID", "FullName", id);

            } else
            {
                ViewBag.WardID = new SelectList(userWards(UserID), "WardID", "FullName");
            }

            
            
            
     return View(r);
 }

 // POST: Reports/Create
 // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
 // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
 [HttpPost]
 [ValidateAntiForgeryToken]
 public ActionResult Create([Bind(Include = "ReportID,WardID,UserID,StateCode,PeriodStartMonth,PeriodStartYear,PeriodDuration,CreateDate,LastUpdated,SubmittedDate,DeletedDate")] Report report)
 {
     if (ModelState.IsValid)
     {
         report.CreateDate = DateTime.Now;
         report.LastUpdated = DateTime.Now;
         db.Reports.Add(report);
         db.SaveChanges();
         return RedirectToAction("Index", new { id = report.WardID });
     }

     ViewBag.UserID = User.Identity.GetUserId();
     ViewBag.WardID = new SelectList(userWards(report.UserID), "WardID", "FullName", report.WardID);
     return View(report);
 }

 // GET: Reports/Edit/5
 public ActionResult Edit(int? id)
 {
     if (id == null)
     {
         // index when no id passed
         return RedirectToAction("Index");
     }
     Report report = db.Reports.Find(id);
     if (report == null)
     {
         return HttpNotFound();
     }
     else if (report.DeletedDate != null)
     {
        // don't show deleted records
        return HttpNotFound();
     }
     ViewBag.UserID = report.UserID;
     //var wards = db.Wards.Where(w => w.UserID == report.UserID);
     ViewBag.WardID = new SelectList(userWards(report.UserID), "WardID", "FullName");
     return View(report);
 }

 // POST: Reports/Edit/5
 // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
 // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
 [HttpPost]
 [ValidateAntiForgeryToken]
 public ActionResult Edit([Bind(Include = "ReportID,WardID,UserID,StateCode,PeriodStartMonth,PeriodStartYear,PeriodDuration,CreateDate")] Report report)
 {
     if (ModelState.IsValid)
     {
        report.LastUpdated = DateTime.Now;
        db.Entry(report).State = EntityState.Modified;
         db.SaveChanges();
         return RedirectToAction("Index", new { id = report.WardID });
     }
     ViewBag.UserID = report.UserID;
     ViewBag.WardID = new SelectList(userWards(report.UserID), "WardID", "FullName");
     return View(report);
 }

 // GET: Reports/Delete/5
 public ActionResult Delete(int? id)
 {
     if (id == null)
     {
         // index when no id passed
         return RedirectToAction("Index");
     }
     Report report = db.Reports.Find(id);
     if (report == null)
     {
         return HttpNotFound();
     }
     else if (report.DeletedDate != null)
     {
        // don't show deleted records
        return HttpNotFound();
     }
     ViewBag.UserID = report.UserID;
     return View(report);
 }

 // POST: Reports/Delete/5
 [HttpPost, ActionName("Delete")]
 [ValidateAntiForgeryToken]
 public ActionResult DeleteConfirmed(int id)
 {
     // todo: change this to only set the DeletedDate;
     Report report = db.Reports.Find(id);
     db.Reports.Remove(report);
     db.SaveChanges();
     return RedirectToAction("Index");
 }

 protected override void Dispose(bool disposing)
 {
     if (disposing)
     {
         db.Dispose();
     }
     base.Dispose(disposing);
 }
}
    
}

Controllers/WardsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GFR.Models;
using Microsoft.AspNet.Identity;

namespace GFR.Controllers
{
    [Authorize]
    public class WardsController : Controller
    {
        private GuardianshipDB db = new GuardianshipDB();

        // GET: Wards
        public ActionResult Index()
        {
            string UserID = User.Identity.GetUserId();
            ViewBag.UserID = UserID; // User.Identity.GetUserId();
            // var wards = db.Wards.Include(w => w.AspNetUser).Where(w => w.UserID == UserID);
            var wards = db.Wards.Where(w => w.UserID == UserID)
                .Where(w => w.DeletedDate == null);


            return View(wards.ToList());
        }

        // GET: Wards/Details/5
        public ActionResult Details(int? id)
        {
            // ViewBag.UserID = User.Identity.GetUserId();
            if (id == null)
            {
                // index when no id passed
                return RedirectToAction("Index");
            }
            Ward ward = db.Wards.Find(id);
            if (ward == null)
            {
                // index or error
                return HttpNotFound();
            } else if (ward.DeletedDate != null)
            {
                // don't show deleted wards
                return HttpNotFound();
            }

            // ViewBag.UserID = User.Identity.GetUserId();
            ViewBag.UserID = ward.UserID;
            return View(ward);
        }

        // GET: Wards/Create
        public ActionResult Create()
        {
            string UserID = User.Identity.GetUserId();
            ViewBag.UserID = UserID; // User.Identity.GetUserId();
            Ward ward = new Ward();
            ward.UserID = UserID;
             
            List<UserSetting> defaults = db.UserSettings.Where(u => u.UserID == UserID).ToList();

            foreach (UserSetting u in defaults)
            {
                if (u.Setting.ToUpper() == ReportValues.REPORT_SETTING_PERIOD_DURATION.ToUpper())
                {

                    ward.PeriodDuration = Convert.ToByte(u.Value);

                }
                else if (u.Setting.ToUpper() == ReportValues.REPORT_SETTING_PERIOD_START_MONTH.ToUpper())
                {
                    ward.PeriodStartMonth = Convert.ToByte(u.Value);

                }
            }

            return View(ward);

            //return View();
        }

        // POST: Wards/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "WardID,UserID,FirstName,MiddleName,LastName,Suffix,Gender,PeriodStartMonth,PeriodDuration,CreateDate,LastUpdated,DeletedDate")] Ward ward)
        {
            if (ModelState.IsValid)
            {
                if (string.IsNullOrEmpty(ward.MiddleName))
                {
                    ward.MiddleName = "";
                }
                if (string.IsNullOrEmpty(ward.Suffix))
                {
                    ward.Suffix = "";
                }
                ward.CreateDate = DateTime.Now;
                ward.LastUpdated = DateTime.Now;
                db.Wards.Add(ward);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            // ViewBag.UserID = User.Identity.GetUserId();
            ViewBag.UserID = ward.UserID;
            return View(ward);
        }

        // GET: Wards/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                // index when no id passed
                return RedirectToAction("Index");
            }
            Ward ward = db.Wards.Find(id);
            if (ward == null)
            {
                // index or error
                return HttpNotFound();
            }
            else if (ward.DeletedDate != null)
            {
                // don't show deleted wards
                return HttpNotFound();
            }


            // ViewBag.UserID = User.Identity.GetUserId();
            // ViewBag.UserID = User.Identity.GetUserId();
            ViewBag.UserID = ward.UserID;
            return View(ward);
        }

        // POST: Wards/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "WardID,UserID,FirstName,MiddleName,LastName,Suffix,Gender,PeriodStartMonth,PeriodDuration,CreateDate")] Ward ward)
        {
            if (ModelState.IsValid)
            {
                if (string.IsNullOrEmpty(ward.MiddleName))
                {
                    ward.MiddleName = "";
                }
                if (string.IsNullOrEmpty(ward.Suffix))
                {
                    ward.Suffix = "";
                }
                ward.LastUpdated = DateTime.Now;
                db.Entry(ward).State = EntityState.Modified;
                db.SaveChanges();

                //try
                //{
                //} catch (Exception e)
                //{
                //    Console.WriteLine(e.Message); 
                //}
                return RedirectToAction("Index");
            }
            //ViewBag.UserID = User.Identity.GetUserId();
            ViewBag.UserID = ward.UserID;
            return View(ward);
        }

        // GET: Wards/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                // index when no id passed
                return RedirectToAction("Index");
            }
            Ward ward = db.Wards.Find(id);
            if (ward == null)
            {
                // index or error
                return HttpNotFound();
            }
            else if (ward.DeletedDate != null)
            {
                // don't show deleted wards
                return HttpNotFound();
            }

            ViewBag.UserID = ward.UserID;
            return View(ward);
        }

        // POST: Wards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            // todo: change this to only set the DeletedDate;
            Ward ward = db.Wards.Find(id);
            db.Wards.Remove(ward);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Reports/Create.cshtml
@model GFR.Models.Report

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>New Report</h4>
<div>
    <a href="@Url.Action("Index", "Reports", new { id = Model.WardID })" title="Back to List"><span class="glyphicon glyphicon-backward" aria-hidden="true"></span></a>
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    @Html.Hidden("UserID", (string)ViewBag.UserID)
    <div class="form-horizontal">
        <h4>Report</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.WardID, "WardID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("WardID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.WardID, "", new { @class = "text-danger" })
            </div>
        </div>

        <!--
        <div class="form-group">
            @Html.LabelFor(model => model.StateCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.StateCode, new { disabled = "disabled", @readonly = "readonly", style = "width: 30px;" })
                </div>
            </div>
        </div>
        -->



        <div class="form-group">
            @Html.LabelFor(model => model.PeriodStartMonth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.PeriodStartMonth, new SelectList(
                  new List<Object>{
                      new { value = "1" , text = "Jan" },
                      new { value = "2" , text = "Feb" },
                      new { value = "3" , text = "Mar" },
                      new { value = "4" , text = "Apr" },
                      new { value = "5" , text = "May" },
                      new { value = "6" , text = "Jun" },
                      new { value = "7" , text = "Jul" },
                      new { value = "8" , text = "Aug" },
                      new { value = "9" , text = "Sep" },
                      new { value = "10" , text = "Oct" },
                      new { value = "11" , text = "Nov" },
                       new { value = "12" , text = "Dec"}
                    },
                  "value",
                  "text"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PeriodStartMonth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PeriodStartYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.PeriodStartYear, new SelectList(
                  new List<Object>{
                      new { value = "2016" , text = "2016" },
                      new { value = "2017" , text = "2017" },
                      new { value = "2018" , text = "2018" },
                      new { value = "2019" , text = "2019" }
                    },
                  "value",
                  "text"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PeriodStartYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PeriodDuration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.PeriodDuration, new SelectList(
                  new List<Object>{
                      new { value = "12" , text = "1 Year" },
                      new { value = "24" , text = "2 Years" },
                      new { value = "36" , text = "3 Years" }
                    },
                  "value",
                  "text"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PeriodDuration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Reports/Delete.cshtml
@model GFR.Models.Report

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Report</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ward.UserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ward.UserID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PeriodStartMonth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PeriodStartMonth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PeriodStartYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PeriodStartYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PeriodDuration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PeriodDuration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastUpdated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastUpdated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubmittedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubmittedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeletedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeletedDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Reports/Details.cshtml
@model GFR.Models.Report

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.HiddenFor(model => model.UserID)
<div>
    <h3>Report</h3>
    <div>
        <a href="@Url.Action("Index", "Reports")" title="Back to List" style="margin-right: 5px;"><span class="glyphicon glyphicon-backward" aria-hidden="true"></span></a>
        <a href="@Url.Action("Edit", "Reports", new { id = Model.ReportID })" title="Edit"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
    </div>
    <hr />
    <dl class="dl-horizontal">
        need ward name
        <dt>
            Ward
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ward.UserID)

            need ward name here
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PeriodStartMonth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PeriodStartMonth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PeriodStartYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PeriodStartYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PeriodDuration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PeriodDuration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastUpdated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastUpdated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubmittedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubmittedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeletedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeletedDate)
        </dd>

    </dl>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Reports/Index.cshtml
@model GFR.ViewModels.ReportViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- was .Models.Report -->
<h2>Reports List</h2>

<p>
@using (Html.BeginForm("Index", "Reports", FormMethod.Post))
{
    <table>
        <tr>
            <td style="vertical-align: middle;">
    @{
        if ((Model.WardsList.ToList().Count == 0) || (Model.SelectedWardID < 1))
        {
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
        }
        else
        {
            <a href="@Url.Action("Create", "Reports", new { id = Model.SelectedWardID })" title="Create new report"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span></a>
        }
    }
        

        </td>
            
            <td style="vertical-align:top;">
                @{
                    // if no list exists, disable + button, hide select list, and display message
                    if (Model.WardsList.ToList().Count == 0)
                    {
                        @Html.ActionLink("You must create a Ward before creating a report.", "Index", "Wards");
                    }
                    else
                    {
                        List<SelectListItem> listItems = new List<SelectListItem>();
                        listItems.Add(new SelectListItem
                        {
                            Text = "",
                            Value = "0"
                        });
                        foreach (var item in Model.WardsList.ToList())
                        {
                            listItems.Add(new SelectListItem
                            {
                                Text = item.FullName,
                                Value = item.WardID.ToString(),
                                Selected = (Model.SelectedWardID == item.WardID ? true : false)
                            });
                        }
                        @Html.DropDownList("id", listItems, new { @class = "form-control", @style = "display-inline", @onchange = "this.form.submit();" });
                    }
                }
                
            </td>
        </tr>

    </table>
}
    
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Report.Ward.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Report.PeriodText)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Report.DurationText)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Report.CreateDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Report.LastUpdated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Report.SubmittedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Report.StatusText)
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model.ReportsList.ToList()) {
    <tr>
        
        <td>
            @Html.DisplayFor(modelItem => item.Ward.FullName )
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PeriodText)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DurationText)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreateDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastUpdated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SubmittedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StatusText)
        </td>
        <td>
            <a href="@Url.Action("Edit", "Reports", new { id = item.ReportID })" title="Edit report"><span class="glyphicon glyphicon-pencil" aria-hidden="true" style="margin-right: 5px;"></span></a>
            <a href="@Url.Action("Reports", "Reports", new { id = item.ReportID })" title="View report"><span class="glyphicon glyphicon-file" aria-hidden="true" style="margin-right: 5px;"></span></a>
            <a href="@Url.Action("Delete", "Reports", new { id = item.ReportID })" title="Delete report"><span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span></a>

        </td>
    </tr>
}



</table>

<div class="text-right">
    <br />
    <a href="@Url.Action("Index", "UserSettings")" title="Modify report settings"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span></a>
</div>