Models/UserCategory.cs
namespace GFR.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("UserCategory")]
    public partial class UserCategory
    {
        private const string WA = "WA";
        private string stateCode = WA; // initially, we only support Washington

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserCategory()
        {
            ReportDetails = new HashSet<ReportDetail>();
        }

        [Key]
        public int CategoryID { get; set; }

        [Required]
        [StringLength(128)]
        public string UserID { get; set; }

        [Required]
        [StringLength(2)]
        [Display(Name = "State")]
        public string StateCode
        {
            get
            {
                return stateCode;
            }
            set
            {
                //stateCode = value;
                stateCode = WA;
            }
        }

        [Display(Name = "Type")]
        [Range(0, 1)]
        [Required(ErrorMessage = @"Type must be ""Income"" (0) or ""Expense"" (1)")]
        public CategoryEnums.CategoryTypes CategoryType { get; set; }

        [Display(Name = "Behavior")]
        [Range(0, 1)]
        [Required(ErrorMessage = @"Behavior must be ""Single-entry"" (0) or ""Multi-entry"" (1)")]
        public CategoryEnums.CategoryBehaviors CategoryClass { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Category Name")]
        public string CategoryName { get; set; }

        [Display(Name = "Display Order")]
        [Required(ErrorMessage = @"Field must be between 0 and 255")]
        public byte Ordinal { get; set; }

        [Display(Name = "Hidden")]
        public bool Hide { get; set; }


        public virtual AspNetUser AspNetUser { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportDetail> ReportDetails { get; set; }
    }
}

Controllers/UserCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GFR.Models;
using Microsoft.AspNet.Identity;

namespace GFR.Controllers
{
    [Authorize]
    public class UserCategoriesController : Controller
    {
        private GuardianshipDB db = new GuardianshipDB();

        // GET: UserCategories
        public ActionResult Index()
        {
            string UserID = User.Identity.GetUserId();
            ViewBag.UserID = UserID; // User.Identity.GetUserId();

            // var userCategories = db.UserCategories.Include(u => u.AspNetUser).Where(u => u.UserID == UserID);
            var userCategories = db.UserCategories.Where(u => u.UserID == UserID)
                .Where(u => u.Hide == false);
            return View(userCategories.ToList()
                .OrderBy(u => u.StateCode)
                .ThenBy(u => u.CategoryType)
                .ThenBy(u => u.Ordinal));
            
        }

        // GET: UserCategories/Details/5
        public ActionResult Details(int? id)
        {
            // ViewBag.UserID = User.Identity.GetUserId();
            if (id == null)
            {
                // index when no id passed
                return RedirectToAction("Index");
            }
            UserCategory userCategory = db.UserCategories.Find(id);
            if (userCategory == null)
            {
                return HttpNotFound();
            }
            // prevent hidden categories from being shown?

            ViewBag.UserID = userCategory.UserID;  
            return View(userCategory);
        }

        // GET: UserCategories/Create
        public ActionResult Create()
        {
            ViewBag.UserID = User.Identity.GetUserId();
            UserCategory uc = new UserCategory { UserID = ViewBag.UserID };
            return View(uc);
        }

        // POST: UserCategories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoryID,UserID,StateCode,CategoryType,CategoryClass,CategoryName,Ordinal")] UserCategory userCategory)
        {
            if (ModelState.IsValid)
            {
                // userCategory.Hide = false;
                db.UserCategories.Add(userCategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserID = User.Identity.GetUserId();
            return View(userCategory);
        }

        // GET: UserCategories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                // index when no id passed
                return RedirectToAction("Index");
            }
            UserCategory userCategory = db.UserCategories.Find(id);
            if (userCategory == null)
            {
                return HttpNotFound();
            }
            // prevent hidden categories from being shown?
            // ViewBag.UserID = User.Identity.GetUserId();
            ViewBag.UserID = userCategory.UserID;
            return View(userCategory);
        }

        // POST: UserCategories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategoryID,UserID,StateCode,CategoryType,CategoryClass,CategoryName,Ordinal")] UserCategory userCategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            // ViewBag.UserID = User.Identity.GetUserId();
            ViewBag.UserID = userCategory.UserID;
            return View(userCategory);
        }

        // GET: UserCategories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                // index when no id passed
                return RedirectToAction("Index");
            }
            UserCategory userCategory = db.UserCategories.Find(id);
            if (userCategory == null)
            {
                return HttpNotFound();
            }
            return View(userCategory);
        }

        // POST: UserCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            // todo: change this to only set the "Hide" flag
            UserCategory userCategory = db.UserCategories.Find(id);
            db.UserCategories.Remove(userCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/UserCategories/Create.cshtml
@model GFR.Models.UserCategory

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<h4>Category</h4>
<div>
    <a href="@Url.Action("Index", "UserCategories")" title="Back to List"><span class="glyphicon glyphicon-backward" aria-hidden="true"></span></a>
</div>
<hr />
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("UserID", (string)ViewBag.UserID)
        <div class="form-horizontal">
            
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            
            <div class="form-group">
                @Html.LabelFor(model => model.StateCode, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.StateCode, new  { disabled = "disabled", @readonly = "readonly", style = "width: 30px;" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CategoryType, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.CategoryType, new SelectList(
                  new List<Object>{
                      new { value = "1" , text = "Expense" },
                       new { value = "0" , text = "Income"}
                    },
                  "value",
                  "text"), new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CategoryType, "", new { @class = "text-danger" })

                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CategoryClass, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EnumDropDownListFor(m => m.CategoryClass, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CategoryClass, "", new { @class = "text-danger" })
                    
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Ordinal, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Ordinal, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Ordinal, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <!--
            <div class="form-group">
                @Html.LabelFor(model => model.Hide, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Hide)
                        @Html.ValidationMessageFor(model => model.Hide, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
             -->
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/UserCategories/Delete.cshtml
@model GFR.Models.UserCategory

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h3>Delete Category Record</h3>

<h3>Are you sure you want to delete this category?</h3>
<div>

    <span class="text-danger">CAUTION: Deleting this category will immediately remove it from all reports, including any previously saved reports.</span>

    <div>
        <a href="@Url.Action("Index", "UserCategories")" title="Back to List"><span class="glyphicon glyphicon-backward" aria-hidden="true"></span></a>
    </div>
    <hr />
    <dl class="dl-horizontal">
        
        <dt>
            @Html.DisplayNameFor(model => model.CategoryType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoryClass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryClass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ordinal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ordinal)
        </dd>
        <!--
        <dt>
            @Html.DisplayNameFor(model => model.Hide)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hide)
        </dd>
        -->


    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    }
</div>

Views/UserCategories/Details.cshtml
@model GFR.Models.UserCategory

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.HiddenFor(model => model.UserID)

    <div>
        <h3>UserCategory</h3>
        <div>
            <a href="@Url.Action("Index", "UserCategories")" title="Back to List" style="margin-right: 5px;"><span class="glyphicon glyphicon-backward" aria-hidden="true"></span></a>
            <a href="@Url.Action("Edit", "UserCategories", new { id = Model.CategoryID })" title="Edit"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
        </div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.StateCode)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.StateCode)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CategoryClass)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CategoryClass)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CategoryName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CategoryName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Ordinal)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Ordinal)
            </dd>
    
            <!--
            <dt>
                @Html.DisplayNameFor(model => model.Hide)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Hide)
            </dd>
            -->
    
        </dl>
    </div>
 

Views/UserCategories/Edit.cshtml
@model GFR.Models.UserCategory

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Edit Category</h3>

<div class="text-danger">CAUTION: Any changes made to this screen will immediate affect reports using this category, including any previously saved reports.</div>


<div>
    <a href="@Url.Action("Index", "UserCategories")" title="Back to List"><span class="glyphicon glyphicon-backward" aria-hidden="true"></span></a>
</div>
<hr />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.CategoryID)
            @Html.HiddenFor(model => model.UserID)
            
            <div class="form-group">
                @Html.LabelFor(model => model.StateCode, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.StateCode, new { disabled = "disabled", @readonly = "readonly", style = "width: 30px;" })
                    </div>
                </div>
            </div>
               
            <div class="form-group">
                @Html.LabelFor(model => model.CategoryType, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.CategoryType, new SelectList(
                  new List<Object>{
                      new { value = "1" , text = "Expense" },
                       new { value = "0" , text = "Income"}
                    },
                  "value",
                  "text"), new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CategoryType, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CategoryClass, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.CategoryClass, new SelectList(
                  new List<Object>{
                      new { value = "0" , text = "Single entry per month" },
                       new { value = "1" , text = "Multiple entries per month"}
                    },
                  "value",
                  "text"), new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CategoryClass, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Ordinal, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Ordinal, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Ordinal, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <!--
            <div class="form-group">
                @Html.LabelFor(model => model.Hide, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Hide)
                        @Html.ValidationMessageFor(model => model.Hide, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
             -->
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
  
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/UserCategories/Index.cshtml
@model IEnumerable<GFR.Models.UserCategory>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h3>Report Categories</h3>   
<p>
    <a href="@Url.Action("Index", "UserSettings")" title="Back to Settings"><span class="glyphicon glyphicon-backward" aria-hidden="true"></span></a>
    <a href="@Url.Action("Create", "UserCategories")" title="Create new category"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span></a>
</p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StateCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoryType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoryClass)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoryName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ordinal)
            </th>
            <!--
            <th>
                @Html.DisplayNameFor(model => model.Hide)
            </th>
            -->

            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StateCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryClass)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ordinal)
            </td>
            <!--
            <td>
                @Html.DisplayFor(modelItem => item.Hide)
            </td>
            -->
            <td>
                <a href="@Url.Action("Edit", "UserCategories", new { id = item.CategoryID })" title="Edit category record"><span class="glyphicon glyphicon-pencil" aria-hidden="true" style="margin-right: 5px;"></span></a>
                <!-- <a href="@Url.Action("Details", "UserCategories", new { id = item.CategoryID })" title="View category record"><span class="glyphicon glyphicon-info-sign" aria-hidden="true" style="margin-right: 5px;"></span></a> -->
                <a href="@Url.Action("Delete", "UserCategories", new { id = item.CategoryID })" title="Delete category record"><span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span></a>
            </td>
        </tr>
    }
    
    </table>