Models/UserSetting.cs
namespace GFR.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class UserSetting
    {
        [Key]
        [Column(Order = 0)]
        public string UserID { get; set; }

        [Key]
        [Column(Order = 1)]
        [StringLength(50)]
        public string Group { get; set; }

        [Key]
        [Column(Order = 2)]
        [StringLength(50)]
        public string Setting { get; set; }

        [Required]
        public string Value { get; set; }

        [StringLength(50)]
        [Display(Name = "Setting")]
        public string FriendlyName { get; set; }

        [StringLength(255)]
        public string Description { get; set; }

        public virtual AspNetUser AspNetUser { get; set; }
    }
}

Controllers/UserSettingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GFR.Models;
using Microsoft.AspNet.Identity;

namespace GFR.Controllers
{
    [Authorize]
    public class UserSettingsController : Controller
    {
        private GuardianshipDB db = new GuardianshipDB();

        // GET: UserSettings
        public ActionResult Index()
        {
            string UserID = User.Identity.GetUserId();
            ViewBag.UserID = UserID; // User.Identity.GetUserId();
            // var userSettings = db.UserSettings.Include(u => u.AspNetUser).Where(u => u.UserID == UserID);
            var userSettings = db.UserSettings.Where(u => u.UserID == UserID);
            return View(userSettings.ToList());
        }

        //// GET: UserSettings/Details/5
        //public ActionResult Details(string id)
        //{
        //    ViewBag.UserID = User.Identity.GetUserId();
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    UserSetting userSetting = db.UserSettings.Find(id);
        //    if (userSetting == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(userSetting);
        //}

        //// GET: UserSettings/Create
        //public ActionResult Create()
        //{
        //    ViewBag.UserID = User.Identity.GetUserId();
        //    return View();
        //}

        //// POST: UserSettings/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "UserID,Group,Setting,Value")] UserSetting userSetting)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.UserSettings.Add(userSetting);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.UserID = User.Identity.GetUserId();
        //    return View(userSetting);
        //}

        // GET: UserSettings/Edit/5
        public ActionResult Edit(string group, string setting)
        {

            if ((group == null) || (setting == null))
            {
                // index when insufficient info passed
                return RedirectToAction("Index");
            }
            ViewBag.UserID = User.Identity.GetUserId();
            UserSetting userSetting = db.UserSettings.Find(ViewBag.UserID, group, setting);
            if (userSetting == null)
            {
                return HttpNotFound();
            }

            switch (setting)
            {
                case ReportValues.REPORT_SETTING_PERIOD_DURATION:
                    // cast as specific 
                    GFR.ViewModels.SettingReportDuration srd = new ViewModels.SettingReportDuration(userSetting);
                    //srd.UserSetting = userSetting;
                    return View("ReportDuration", srd);
                    break;
                case ReportValues.REPORT_SETTING_PERIOD_START_MONTH:
                    GFR.ViewModels.SettingReportStartMonth srm = new ViewModels.SettingReportStartMonth(userSetting);
                    //srm.UserSetting = userSetting;
                    return View("ReportStartMonth", srm);
                    break;
                default:
                    GFR.ViewModels.SettingReportStartYear sry = new ViewModels.SettingReportStartYear(userSetting);
                    //sry.UserSetting = userSetting;
                    return View("ReportStartYear", sry);
                    break;
            }
            return View(userSetting);
        }

        // POST: UserSettings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserID,Group,Setting,Value,FriendlyName,Description")] UserSetting userSetting)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userSetting).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            // ViewBag.UserID = User.Identity.GetUserId();
            ViewBag.UserID = userSetting.UserID;
            return View(userSetting);
        }

        //// GET: UserSettings/Delete/5
        //public ActionResult Delete(string id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    UserSetting userSetting = db.UserSettings.Find(id);
        //    if (userSetting == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(userSetting);
        //}

        //// POST: UserSettings/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(string id)
        //{
        //    UserSetting userSetting = db.UserSettings.Find(id);
        //    db.UserSettings.Remove(userSetting);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/UserSettings/Edit.cshtml
@model GFR.Models.UserSetting

@{
    ViewBag.Title = "Edit";
}

<h3>Edit Setting</h3>
<div>
    <a href="@Url.Action("Index", "UserSettings")" title="Back to List"><span class="glyphicon glyphicon-backward" aria-hidden="true"></span></a>
</div>
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserID)

        @Html.HiddenFor(model => model.Group)

        @Html.HiddenFor(model => model.Setting)
        @Html.HiddenFor(model => model.FriendlyName)
        @Html.HiddenFor(model => model.Description)

        <div class="form-group">
            @Html.LabelFor(model => model.FriendlyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.FriendlyName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Views/UserSettings/Index.cshtml
@model IEnumerable<GFR.Models.UserSetting>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Settings</h3>   

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Group)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FriendlyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Value)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td title="@item.Description">
                @Html.DisplayFor(modelItem => item.Group)
            </td>
            <td title="@item.Description">
                @Html.DisplayFor(modelItem => item.FriendlyName)
            </td>
            <td title="@item.Description">
                @Html.DisplayFor(modelItem => item.Value)
            </td>
            <td>
                <a href="@Url.Action("Edit", "UserSettings", new { group = item.Group, setting = item.Setting  })" title='Edit "@item.Description" record'><span class="glyphicon glyphicon-pencil" aria-hidden="true" style="margin-right: 5px;"></span></a>
            </td>
        </tr>
    }

    <tr>
        <td colspan="3"></td>
        <td>
            <div class="text-right">
                <br />
                <a href="@Url.Action("Index", "UserCategories")" title="Modify report categories (CAUTION!)">Report Categories</a>
            </div>
        </td>

    </tr>

</table>

Views/UserSettings/ReportDuration.cshtml
@model GFR.ViewModels.SettingReportDuration

@{
    ViewBag.Title = "Edit";
}

<h3>Edit Setting</h3>
<div>
    <a href="@Url.Action("Index", "UserSettings")" title="Back to List"><span class="glyphicon glyphicon-backward" aria-hidden="true"></span></a>
</div>
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserID)

        @Html.HiddenFor(model => model.Group)

        @Html.HiddenFor(model => model.Setting)
        @Html.HiddenFor(model => model.FriendlyName)
        @Html.HiddenFor(model => model.Description)

        
        <div class="form-group">
            @Html.LabelFor(model => model.FriendlyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.FriendlyName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DurationType, "Value", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Value",
                   EnumHelper.GetSelectList(typeof(ReportValues.DurationTypes)),
                   "Select Report Period",
                   new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })

            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Views/UserSettings/ReportStartMonth.cshtml
@model GFR.ViewModels.SettingReportStartMonth

@{
    ViewBag.Title = "Edit";
}

<h3>Edit Setting</h3>
<div>
    <a href="@Url.Action("Index", "UserSettings")" title="Back to List"><span class="glyphicon glyphicon-backward" aria-hidden="true"></span></a>
</div>
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserID)

        @Html.HiddenFor(model => model.Group)

        @Html.HiddenFor(model => model.Setting)
        @Html.HiddenFor(model => model.FriendlyName)
        @Html.HiddenFor(model => model.Description)

        <div class="form-group">
            @Html.LabelFor(model => model.FriendlyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.FriendlyName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartMonth, "Value", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Value",
                   EnumHelper.GetSelectList(typeof(ReportValues.MonthTypes)),
                   "Select Start Month",
                   new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })

            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Views/UserSettings/ReportStartYear.cshtml
@model GFR.ViewModels.SettingReportStartYear

@{
    ViewBag.Title = "Edit";
}

<h3>Edit Setting</h3>
<div>
    <a href="@Url.Action("Index", "UserSettings")" title="Back to List"><span class="glyphicon glyphicon-backward" aria-hidden="true"></span></a>
</div>
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserID)

        @Html.HiddenFor(model => model.Group)

        @Html.HiddenFor(model => model.Setting)
        @Html.HiddenFor(model => model.FriendlyName)
        @Html.HiddenFor(model => model.Description)

        
        <div class="form-group">
            @Html.LabelFor(model => model.FriendlyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.FriendlyName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartYear, "Value", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StartYear, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}